payload = {
      "leadId": "oZI8xIIdGkgqf4ZNdzLUT",
      "codigoPlantilla": "2070",
      "numeroContrato": 107,
      "rutSponsor": 96656410,
      "dvSponsor": "5",
      "token": None,
      "terminoVigencia": None,
      "numeroPoliza": None,
      "medioDePago": 1,
      "ahorros": [],
      "formaPagoReembolso": 1,
      "plan": 238,
      "valorNetoPlan": 0.362,
      "valorIvaPlan": 0.082,
      "fechaInicioVigencia": "20221013",
      "fechaVenta": "15:36:12",
      "primaTotal": 0.431,
      "rutContratante": 13095676,
      "dvContratante": "9",
      "apellidoPaternoContratante": "Arredondo",
      "apellidoMaternoContratante": "Reyes",
      "nombreContratante": "Vladimir Eduardo",
      "fechaNacimientoContratante": "19640821",
      "sexoContratante": "",
      "domicilioCalleContratante": "De Los Viñedos",
      "domicilioNumeroContratante": "7673",
      "departamentoContratante": "",
      "comunaContratante": "O'higgins",
      "codigoComunaContratante": 11248,
      "regionContratante": "Región Metropolitana de Santiago",
      "telefonoContratante": 994386602,
      "mailContratante": "vatredondo1964@gmail.com",
      "rutAsegurado": 13095676,
      "dvAsegurado": "9",
      "apellidoPaternoAsegurado": "Arredondo",
      "apellidoMaternoAsegurado": "Reyes",
      "nombreAsegurado": "Vladimir Eduardo",
      "fechaNacimientoAsegurado": "19640821",
      "sexoAsegurado": "",
      "relacionConContratante": 1,
      "domicilioCalleAsegurado": "De Los Viñedos",
      "domicilioNumeroAsegurado": "7673",
      "departamentoAsegurado": "",
      "comunaAsegurado": "O'higgins",
      "codigoComunaAsegurado": 11248,
      "institucionSalud": 9,
      "banco": "12",
      "tipoCuentaReembolso": "2",
      "numeroCuentaReembolso": "10482933",
      "email": "vatredondo1964@gmail.com",
      "username": "oZI8xIIdGkgqf4ZNdzLUT",
      "tbkUser": "043f27b9-713d-4cd5-a340-2c6dff3b647c",
      "numeroTarjeta": "1600",
      "tipoTarjeta": "RedCompra",
      "numeroPropuesta": "2022101212360944531",
      "periodoProximoCobro": "01/11/2022",
      "rutVendedor": 10482933,
      "dvVendedor": "3",
      "nombreVendedor": "Susana De Las Nieves,Zuniga Contreras",
      "preexistencias": [],
      "coberturas": [
          {
              "idCobertura": 86,
              "capitalUf": 200,
              "primaBrutaPesos": 9391,
              "primaBrutaUf": 0.273,
              "primaNetaUf": 0.2294
          }
      ],
      "cargas": []
}